[Running] node "/home/thesynthax/test/test.js"
Hello, world

[Done] exited with code=0 in 0.114 seconds

[Running] node "/home/thesynthax/test/test.js"
Hello, world
bitch

[Done] exited with code=0 in 0.089 seconds

[Running] node "/home/thesynthax/test/test.js"
Hello, world
bitch

[Done] exited with code=0 in 0.098 seconds

[Running] node "/home/thesynthax/test/test.js"
Hello, world
bitch

[Done] exited with code=0 in 0.092 seconds

[Running] node "/home/thesynthax/test/test.js"
Hello, world
bitch

[Done] exited with code=0 in 0.097 seconds

[Running] node "/home/thesynthax/test/test.js"
sexfuck

[Done] exited with code=0 in 0.097 seconds

[Running] node "/home/thesynthax/test/test.js"
sexfuck

[Done] exited with code=0 in 0.097 seconds

[Running] node "/home/thesynthax/test/test.js"
sexbitch

[Done] exited with code=0 in 0.097 seconds

[Running] node "/home/thesynthax/test/test.js"
/home/thesynthax/test/test.js:3
num.forEach(i) => 
    ^^^^^^^^^

SyntaxError: Malformed arrow function parameter list
    at internalCompileFunction (node:internal/vm:74:18)
    at wrapSafe (node:internal/modules/cjs/loader:1141:20)
    at Module._compile (node:internal/modules/cjs/loader:1182:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.3.0

[Done] exited with code=1 in 0.138 seconds

[Running] node "/home/thesynthax/test/test.js"
/home/thesynthax/test/test.js:4
    console.log(i)
                ^

ReferenceError: i is not defined
    at /home/thesynthax/test/test.js:4:17
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/thesynthax/test/test.js:3:5)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.3.0

[Done] exited with code=1 in 0.127 seconds

[Running] node "/home/thesynthax/test/test.js"
1
2
3
4
5
6

[Done] exited with code=0 in 0.1 seconds

[Running] node "/home/thesynthax/test/test.js"
1
2
3
4
5
6

[Done] exited with code=0 in 0.104 seconds

[Running] node "/home/thesynthax/test/test.js"
1
2
3
4
5
6

[Done] exited with code=0 in 0.119 seconds

[Running] node "/home/thesynthax/test/test.js"
1
2
3
4
5
6

[Done] exited with code=0 in 0.138 seconds

[Running] node "/home/thesynthax/test/test.js"
1
2
3
4
5
6

[Done] exited with code=0 in 0.131 seconds

[Running] node "/home/thesynthax/test/test.js"
1
2
3
4
5
6

[Done] exited with code=0 in 0.093 seconds

[Running] node "/home/thesynthax/test/test.js"
1
8
27
64
125
216

[Done] exited with code=0 in 0.138 seconds

[Running] node "/home/thesynthax/test/test.js"
1
8
27
64
125
216

[Done] exited with code=0 in 0.103 seconds

[Running] node "/home/thesynthax/test/test.js"
/home/thesynthax/test/test.js:2
let a = prompt("FUCK YOU!: ")
        ^

ReferenceError: prompt is not defined
    at Object.<anonymous> (/home/thesynthax/test/test.js:2:9)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.3.0

[Done] exited with code=1 in 0.123 seconds

[Running] node "/home/thesynthax/test/test.js"
/home/thesynthax/test/test.js:2
let a = prompt("FUCK YOU!: ")
        ^

ReferenceError: prompt is not defined
    at Object.<anonymous> (/home/thesynthax/test/test.js:2:9)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.3.0

[Done] exited with code=1 in 0.09 seconds

[Running] node "/home/thesynthax/test/test.js"
/home/thesynthax/test/test.js:2
let a = prompt("FUCK YOU!: ")
        ^

ReferenceError: prompt is not defined
    at Object.<anonymous> (/home/thesynthax/test/test.js:2:9)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.3.0

[Done] exited with code=1 in 0.125 seconds

[Running] node "/home/thesynthax/test/test.js"
/home/thesynthax/test/test.js:2
let a = parseInt(prompt("FUCK YOU!: "))
        ^

ReferenceError: prompt is not defined
    at Object.<anonymous> (/home/thesynthax/test/test.js:2:9)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.3.0

[Done] exited with code=1 in 0.121 seconds

[Running] node "/home/thesynthax/test/test.js"
/home/thesynthax/test/test.js:2
let a = readLine("Hello:")
        ^

ReferenceError: readLine is not defined
    at Object.<anonymous> (/home/thesynthax/test/test.js:2:9)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.3.0

[Done] exited with code=1 in 0.128 seconds

[Running] node "/home/thesynthax/test/test.js"
/home/thesynthax/test/test.js:2
let a = readLine("Hello:")
        ^

ReferenceError: readLine is not defined
    at Object.<anonymous> (/home/thesynthax/test/test.js:2:9)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.3.0

[Done] exited with code=1 in 0.126 seconds

[Running] node "/home/thesynthax/test/test.js"
/home/thesynthax/test/test.js:2
let a = prompt();
        ^

ReferenceError: prompt is not defined
    at Object.<anonymous> (/home/thesynthax/test/test.js:2:9)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.3.0

[Done] exited with code=1 in 0.124 seconds

[Running] node "/home/thesynthax/test/test.js"
/home/thesynthax/test/test.js:2
let a = prompt();
        ^

ReferenceError: prompt is not defined
    at Object.<anonymous> (/home/thesynthax/test/test.js:2:9)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.3.0

[Done] exited with code=1 in 0.123 seconds

[Running] node "/home/thesynthax/test/test.js"
/home/thesynthax/test/test.js:3
a = prompt();
^

ReferenceError: prompt is not defined
    at Object.<anonymous> (/home/thesynthax/test/test.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.3.0

[Done] exited with code=1 in 0.142 seconds

[Running] node "/home/thesynthax/test/test.js"
/home/thesynthax/test/test.js:2
a = prompt();
^

ReferenceError: prompt is not defined
    at Object.<anonymous> (/home/thesynthax/test/test.js:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.3.0

[Done] exited with code=1 in 0.106 seconds

[Running] node "/home/thesynthax/test/test.js"
1
8
27
64
125
216

[Done] exited with code=0 in 0.112 seconds

[Running] node "/home/thesynthax/test/test.js"
1
8
27
64
125
216

[Done] exited with code=0 in 0.129 seconds

[Running] node "/home/thesynthax/test/test.js"
/home/thesynthax/node_modules/prompt-sync/index.js:24
  var autocomplete = config.autocomplete =
                                         ^

TypeError: Cannot create property 'autocomplete' on string 'Hey fuck you: '
    at create (/home/thesynthax/node_modules/prompt-sync/index.js:24:42)
    at Object.<anonymous> (/home/thesynthax/test/test.js:3:5)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.3.0

[Done] exited with code=1 in 0.102 seconds

[Running] node "/home/thesynthax/test/test.js"
/home/thesynthax/node_modules/prompt-sync/index.js:24
  var autocomplete = config.autocomplete =
                                         ^

TypeError: Cannot create property 'autocomplete' on string 'Hey fuck you: '
    at create (/home/thesynthax/node_modules/prompt-sync/index.js:24:42)
    at Object.<anonymous> (/home/thesynthax/test/test.js:3:5)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.3.0

[Done] exited with code=1 in 0.101 seconds

[Running] node "/home/thesynthax/test/test.js"
node:internal/fs/utils:347
    throw err;
    ^

Error: ENXIO: no such device or address, open '/dev/tty'
    at Object.openSync (node:fs:584:3)
    at prompt (/home/thesynthax/node_modules/prompt-sync/index.js:67:10)
    at Object.<anonymous> (/home/thesynthax/test/test.js:3:5)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -6,
  syscall: 'open',
  code: 'ENXIO',
  path: '/dev/tty'
}

Node.js v19.3.0

[Done] exited with code=1 in 0.104 seconds

[Running] node "/home/thesynthax/test/test.js"
node:internal/fs/utils:347
    throw err;
    ^

Error: ENXIO: no such device or address, open '/dev/tty'
    at Object.openSync (node:fs:584:3)
    at prompt (/home/thesynthax/node_modules/prompt-sync/index.js:67:10)
    at Object.<anonymous> (/home/thesynthax/test/test.js:3:5)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -6,
  syscall: 'open',
  code: 'ENXIO',
  path: '/dev/tty'
}

Node.js v19.3.0

[Done] exited with code=1 in 0.141 seconds

[Running] node "/home/thesynthax/test/test.js"
node:internal/fs/utils:347
    throw err;
    ^

Error: ENXIO: no such device or address, open '/dev/tty'
    at Object.openSync (node:fs:584:3)
    at prompt (/home/thesynthax/node_modules/prompt-sync/index.js:67:10)
    at Object.<anonymous> (/home/thesynthax/test/test.js:3:9)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -6,
  syscall: 'open',
  code: 'ENXIO',
  path: '/dev/tty'
}

Node.js v19.3.0

[Done] exited with code=1 in 0.123 seconds

[Running] node "/home/thesynthax/test/test.js"
node:internal/fs/utils:347
    throw err;
    ^

Error: ENXIO: no such device or address, open '/dev/tty'
    at Object.openSync (node:fs:584:3)
    at prompt (/home/thesynthax/node_modules/prompt-sync/index.js:67:10)
    at Object.<anonymous> (/home/thesynthax/test/test.js:3:9)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -6,
  syscall: 'open',
  code: 'ENXIO',
  path: '/dev/tty'
}

Node.js v19.3.0

[Done] exited with code=1 in 0.139 seconds

[Running] node "/home/thesynthax/test/test.js"
node:internal/fs/utils:347
    throw err;
    ^

Error: ENXIO: no such device or address, open '/dev/tty'
    at Object.openSync (node:fs:584:3)
    at prompt (/home/thesynthax/node_modules/prompt-sync/index.js:67:10)
    at Object.<anonymous> (/home/thesynthax/test/test.js:3:9)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -6,
  syscall: 'open',
  code: 'ENXIO',
  path: '/dev/tty'
}

Node.js v19.3.0

[Done] exited with code=1 in 0.309 seconds

[Running] node "/home/thesynthax/test/test.js"
node:internal/fs/utils:347
    throw err;
    ^

Error: ENXIO: no such device or address, open '/dev/tty'
    at Object.openSync (node:fs:584:3)
    at prompt (/home/thesynthax/node_modules/prompt-sync/index.js:67:10)
    at Object.<anonymous> (/home/thesynthax/test/test.js:3:9)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -6,
  syscall: 'open',
  code: 'ENXIO',
  path: '/dev/tty'
}

Node.js v19.3.0

[Done] exited with code=1 in 0.141 seconds

[Running] node "/home/thesynthax/test/test.js"
node:internal/fs/utils:347
    throw err;
    ^

Error: ENXIO: no such device or address, open '/dev/tty'
    at Object.openSync (node:fs:584:3)
    at prompt (/home/thesynthax/node_modules/prompt-sync/index.js:67:10)
    at Object.<anonymous> (/home/thesynthax/test/test.js:3:9)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -6,
  syscall: 'open',
  code: 'ENXIO',
  path: '/dev/tty'
}

Node.js v19.3.0

[Done] exited with code=1 in 0.108 seconds

[Running] node "/home/thesynthax/test/test.js"
node:internal/fs/utils:347
    throw err;
    ^

Error: ENXIO: no such device or address, open '/dev/tty'
    at Object.openSync (node:fs:584:3)
    at prompt (/home/thesynthax/node_modules/prompt-sync/index.js:67:10)
    at Object.<anonymous> (/home/thesynthax/test/test.js:3:9)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -6,
  syscall: 'open',
  code: 'ENXIO',
  path: '/dev/tty'
}

Node.js v19.3.0

[Done] exited with code=1 in 0.108 seconds

[Running] node "/home/thesynthax/test/test.js"
node:internal/fs/utils:347
    throw err;
    ^

Error: ENXIO: no such device or address, open '/dev/tty'
    at Object.openSync (node:fs:584:3)
    at prompt (/home/thesynthax/node_modules/prompt-sync/index.js:67:10)
    at Object.<anonymous> (/home/thesynthax/test/test.js:3:9)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -6,
  syscall: 'open',
  code: 'ENXIO',
  path: '/dev/tty'
}

Node.js v19.3.0

[Done] exited with code=1 in 0.095 seconds

[Running] node "/home/thesynthax/test/test.js"
1
8
27
64
125
216

[Done] exited with code=0 in 0.134 seconds

[Running] node "/home/thesynthax/test/test.js"
1
8
27
64
125
216

[Done] exited with code=0 in 0.136 seconds

[Running] node "/home/thesynthax/test/test.js"
/home/thesynthax/test/test.js:3
let a = prompt("Hey fuck you: ");
        ^

ReferenceError: prompt is not defined
    at Object.<anonymous> (/home/thesynthax/test/test.js:3:9)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.3.0

[Done] exited with code=1 in 0.126 seconds

[Running] node "/home/thesynthax/test/test.js"
node:internal/fs/utils:347
    throw err;
    ^

Error: ENXIO: no such device or address, open '/dev/tty'
    at Object.openSync (node:fs:584:3)
    at prompt (/home/thesynthax/node_modules/prompt-sync/index.js:67:10)
    at Object.<anonymous> (/home/thesynthax/test/test.js:3:9)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -6,
  syscall: 'open',
  code: 'ENXIO',
  path: '/dev/tty'
}

Node.js v19.3.0

[Done] exited with code=1 in 0.141 seconds

[Running] node "/home/thesynthax/test/test.js"
node:internal/fs/utils:347
    throw err;
    ^

Error: ENXIO: no such device or address, open '/dev/tty'
    at Object.openSync (node:fs:584:3)
    at prompt (/home/thesynthax/node_modules/prompt-sync/index.js:67:10)
    at Object.<anonymous> (/home/thesynthax/test/test.js:3:9)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -6,
  syscall: 'open',
  code: 'ENXIO',
  path: '/dev/tty'
}

Node.js v19.3.0

[Done] exited with code=1 in 0.108 seconds

[Running] node "/home/thesynthax/test/test.js"
node:internal/fs/utils:347
    throw err;
    ^

Error: ENXIO: no such device or address, open '/dev/tty'
    at Object.openSync (node:fs:584:3)
    at prompt (/home/thesynthax/node_modules/prompt-sync/index.js:67:10)
    at Object.<anonymous> (/home/thesynthax/test/test.js:3:9)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -6,
  syscall: 'open',
  code: 'ENXIO',
  path: '/dev/tty'
}

Node.js v19.3.0

[Done] exited with code=1 in 0.138 seconds

[Running] node "/home/thesynthax/test/test.js"
node:internal/fs/utils:347
    throw err;
    ^

Error: ENXIO: no such device or address, open '/dev/tty'
    at Object.openSync (node:fs:584:3)
    at prompt (/home/thesynthax/node_modules/prompt-sync/index.js:67:10)
    at Object.<anonymous> (/home/thesynthax/test/test.js:3:9)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -6,
  syscall: 'open',
  code: 'ENXIO',
  path: '/dev/tty'
}

Node.js v19.3.0

[Done] exited with code=1 in 0.137 seconds

